### ISSUE TITLE
Snapshot extension registration failed

### ISSUE THREAD

**Issue by GushALKDev** [bnb-chain/opbnb-node-docker#1]
Hi, the op-geth is not able to reach the latest block, it receives a bunch of blocks and stops, getting several "Snapshot extension registration failed"  err="peer connected on snap without compatible eth support" errors.

After some time, it receives another bunch of blocks to fails again with more "Snapshot extension registration failed" errors.

It is never able to be updated to the latest block.

We tried using public and private full BSC L1 node with same results.

![Screenshot 2023-06-22 at 10 33 49](https://github.com/bnb-chain/opbnb-node-docker/assets/112427468/b5b8cb5b-8f3d-4ac6-9ca4-5cfdffe1c298)

**Comment by owen-reorg** [comment]
As this is an initial problem and the chain has undergone significant changes since then, please follow the instructions and verify if it resolves the issue. If you continue to encounter the problem, kindly reopen it on https://github.com/bnb-chain/opbnb/issues.
