### ISSUE TITLE
Not able to sync block more modern than 12h43s ago

### ISSUE THREAD

**Issue by alfaori1977** [bnb-chain/opbnb-node-docker#4]
My node is always 12h43s behind the current block.. No matter if I start, restart it, the node always adquire new blocks very quickly until it's 12h42s close to the curent block.. From that moment it continues syncing blocks but it's not able to break the 12h43s "frontier"

Could anyone help me?

<img width="508" alt="image" src="https://github.com/bnb-chain/opbnb-node-docker/assets/122934282/1a35f62e-3f22-427c-9973-69885ce7dede">

<img width="790" alt="image" src="https://github.com/bnb-chain/opbnb-node-docker/assets/122934282/c9368dfe-37aa-45b7-a592-4375812b3e25">

**Comment by deepcrazy** [comment]
You can actually build your own docker image by running the opbnb testnet node by following this guide: 
 https://docs.bnbchain.org/opbnb-docs/docs/tutorials/running-a-testnet-node.

P.S: This repo is just for reference only and will be made private down the road. Please try building your own docker image if required or run the opBNB node as per the doc mentioned above.

**Comment by alfaori1977** [comment]
Wow!! There's a very big Leap to go from this [guide ](https://docs.bnbchain.org/opbnb-docs/docs/tutorials/running-a-testnet-node) to generate a working docker image!!! Definitely beyond my knowledge. A quick guide or tutorial will be pretty much appreciated.

Regarding to the issue itself, do you (or anyone) have any clue about the 12h43s limit?

**Comment by owen-reorg** [comment]
> Regarding to the issue itself, do you (or anyone) have any clue about the 12h43s limit?

It is possible that your chain has forked from the canonical chain, resulting in it producing empty blocks according to the protocol. To confirm this, you can compare the block at the same height with the public endpoint.

I am closing this issue for now. Please feel free to reopen it if you have any further questions.
