### ISSUE TITLE
how to fill in OP_NODE__RPC_ENDPOINT

### ISSUE THREAD

**Issue by kugimiya530** [bnb-chain/opbnb-node-docker#6]
OP_NODE__RPC_ENDPOINT=

is this doesn't mean L1 rpc endpoint?

i fill in my geth's rpc endpoint , and can't start syncing

**Comment by owen-reorg** [comment]
There is comment for the field.

```
# L1 node that the op-node will get chain data from
```

Please fill in the L1 (BSC) endpoint. For testing purposes, you can use a public endpoint from [here](https://docs.bnbchain.org/docs/rpc). It is recommended to use a reliable third-party service with a better SLA guarantee, e.g. [menogade](https://nodereal.io/meganode).
